before_install: gem install bundler
before_script:
  - "bundle exec rake test_app"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - nate@finelineautomation.com
branches:
  only:
    - master
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
addons:
  sauce_connect:
    username: "FineLineAutomation"
    jwt:
      secure: "nWsXEtnNNWyH+NGeWnQFNFOlMuCV2L7d8djavxSOwdfo6HrLLNde7Q5OUN5pf3yGQpbc/n9z6NhZaDvlmxHGGfcZMiuGfE/W6ZFeJfxKKdyZcvUPEGQfu+LyEyFlgj94d5b4/7wYQhj9X4BrnX7WnJZZiwGEwhC4Tp7mArE01uQ="